### PR TITLE
Added simple math library

### PR DESCRIPTION
**Pull request by deboogerxyz**

### CODE REVIEW

**Comment by 8dcc** [comment]
I will merge when:
- [ ] All the SSE/SSE2 issues are fixed.
- [ ] I move the inline assembly functions inside `math.c` to a separate `math.asm` file (`sqrt`, `sin`, `cos`, `tan`, `cot`).
- [ ] I add doxygen comments to `math.h`.

**Review by 8dcc — APPROVED** [review]

**Comment by deboogerxyz** [comment]
> I will merge when:
> 
>     * [ ]  All the SSE/SSE2 issues are fixed.
> 
>     * [ ]  I move the inline assembly functions inside `math.c` to a separate `math.asm` file (`sqrt`, `sin`, `cos`, `tan`, `cot`).
> 
>     * [ ]  I add doxygen comments to `math.h`.

SSE issues weren't caused by hand written assembly, but by incorrectly optimized C code by the compiler (memory volatility).
The remaining issues with SSE are not saving XMM registers on context switches.

Inline assembly has been rewritten to external `math.asm`, but it's currently not compiled and the kernel is not linked with it.
Changes to the build system are required for this.

**Comment by deboogerxyz** [comment]
Functions rewritten in assembly are currently broken.

**Comment by deboogerxyz** [comment]
> Functions rewritten in assembly are currently broken.

Fixed.

**Comment by 8dcc** [comment]
All the (known) SSE/FPU/XMM issues have been fixed in #13

If you un-draft this PR, I will merge it after some changes.

**Review by 8dcc — APPROVED** [review]

**Review by 8dcc — APPROVED** [review]

**Comment by 8dcc** [comment]
Thank you for your contribution!

**Pull request merged**
